import { Inter } from "next/font/google";
import "./globals.css";
// 1. 引入 ThemeProvider
import { ThemeProvider } from "@/components/theme-provider"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 2. 使用 ThemeProvider
export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>         
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          themes = {['light', 'dark', 'rose']}
          disableTransitionOnChange
          >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}




